CREATE TABLE FUNCIONARIO(
ID UNIQUEIDENTIFIER PRIMARY KEY,
NOME      VARCHAR(150) NOT NULL,
CPF       VARCHAR(14) NOT NULL,
MATRICULA VARCHAR(10) NOT NULL,
DATAADMISSAO DATE NOT NULL,
TIPOCONTRATACAO INTEGER,
CHECK(TIPOCONTRATACAO IN (1,2,3))

)
GO